CREATE TABLE ZIP(
    Zip VARCHAR(10) PRIMARY KEY,
    City CHAR(20) NOT NULL,
    Customer_State CHAR(20)  NOT NULL DEFAULT 'Ontario',
    CONSTRAINT Customer_City CHECK(City= 'Toronto')
);


INSERT INTO ZIP VALUES('M1K314','Toronto',DEFAULT);
INSERT INTO ZIP VALUES('M1K315','Toronto',DEFAULT);
INSERT INTO ZIP VALUES('M1K316','Toronto',DEFAULT);
INSERT INTO ZIP VALUES('M1K313','Toronto',DEFAULT);
INSERT INTO ZIP VALUES('M1K317','Toronto',DEFAULT);
INSERT INTO ZIP VALUES('M1K319','Toronto',DEFAULT);
INSERT INTO ZIP VALUES('M1K318','Toronto',DEFAULT);
INSERT INTO ZIP VALUES('M1K320','Toronto',DEFAULT);
INSERT INTO ZIP VALUES('M1K323','Toronto',DEFAULT);
INSERT INTO ZIP VALUES('M1K324','Toronto',DEFAULT);


SELECT * FROM ZIP
EXEC Sp_help  ZIP